# Generated by Django 4.2.20 on 2025-05-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
