# Generated by Django 4.2.20 on 2025-05-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(blank=True, help_text='Comma-separated sizes, e.g. XS,S,M,L,XL,XXL', max_length=50),
        ),
    ]
