# Generated by Django 4.2.20 on 2025-05-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_available_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(blank=True, help_text='Selected size for this cart item', max_length=10),
        ),
    ]
