# Generated by Django 4.2.20 on 2025-05-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_cart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(blank=True, help_text='Selected size for this order item', max_length=10),
        ),
    ]
